# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:02
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(default=accounts.models.get_random_id, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0, verbose_name='Balance')),
                ('currency', models.PositiveIntegerField(choices=[(0, 'EUR'), (1, 'USD'), (2, 'GBR'), (3, 'CHF')], default=0, verbose_name='Currency')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Balance')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='accounts.Account', verbose_name='Destination Account')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='accounts.Account', verbose_name='Source Account')),
            ],
        ),
    ]
