version: '3.3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/opt/code
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    env_file: .env
    ports:
      - "127.0.1.1:80:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "127.0.1.0:80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/dist
